os: linux

# Use the latest Ubuntu available now on Travis-CI: 20.04 instead of
# default 16.04 https://docs.travis-ci.com/user/reference/linux/
dist: focal

language: cpp

# Use docker to allow more modern OS in it, so we depart from basic
# https://docs.travis-ci.com/user/languages/cpp/ here
services:
    - docker

env:
  # Launch tests in parallel https://docs.travis-ci.com/user/build-matrix/
  jobs:
    - CC_BUILD=gcc-10
      CXX_BUILD=g++-10
      OPENMP=ON
      OPENCL=OFF

    - CC_BUILD=clang-10
      CXX_BUILD=clang++-10
      OPENMP=ON
      OPENCL=OFF

    - CC_BUILD=gcc-10
      CXX_BUILD=g++-10
      OPENMP=ON
      OPENCL=ON

    - CC_BUILD=clang-10
      CXX_BUILD=clang++-10
      OPENMP=ON
      OPENCL=ON

before_install:
    - |
      # https://docs.travis-ci.com/user/environment-variables/
      if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
         export GIT_SLUG=${TRAVIS_REPO_SLUG}
         export GIT_BRANCH=${TRAVIS_BRANCH}
      else
         export GIT_SLUG=${TRAVIS_PULL_REQUEST_SLUG}
         export GIT_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
      fi
    - echo "Git repo | branch -> ${GIT_SLUG} | ${GIT_BRANCH}"
    - docker build --build-arg cxx_compiler=${CXX_BUILD}
                   --build-arg c_compiler=${CC_BUILD}
                   --build-arg git_branch=${GIT_BRANCH}
                   --build-arg git_slug=${GIT_SLUG}
                   --build-arg openmp=${OPENMP}
                   --build-arg opencl=${OPENCL} -t trisycl .
    - docker ps -a
    - docker images

script:
    - docker run trisycl
